# Generated by Django 5.2.7 on 2025-10-03 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logos_equipos/')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='archivos_jugadores/')),
                ('identifacion_pdf', models.FileField(upload_to='archivos_jugadores/')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.equipo')),
            ],
        ),
    ]
