# Generated by Django 5.2.7 on 2025-10-03 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugador',
            old_name='identifacion_pdf',
            new_name='identificacion_pdf',
        ),
    ]
